version: "3"
services:
  app:
    build: ./web
    container_name: blockchain-web
    networks:
      - web
    ports:
        - "8000:8000"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.blockchain-web.entrypoints=web,websecure"
      - "traefik.http.routers.blockchain-web.rule=Host(`blockchain.gcc-ensibs.fr`)"
      - "traefik.http.services.blockchain-web.loadbalancer.server.port=8000"
      - "traefik.http.routers.blockchain-web.tls=true"
      - "traefik.http.routers.blockchain-web.tls.certresolver=lets-encrypt"
  chain:
    build: ./chain
    container_name: blockchain-chain
    ports:
      - "8545:8545"

networks:
  web:
    external: true